### ISSUE TITLE
constructing and accessing ByteAt, WydeAt, TetraAt, OctaAt

### ISSUE THREAD

**Issue by BarbaraButz** [MMXVII/mmix#22]
We (obviously) need to construct these types and access their fields somehow. We could either declare their respective field public, or implement "constructor-methods" and get-/set-methods. Opinions?
@jaborn @KarolinePlum @teiesti 

Edit: added implementation of ldb for clarification
currently, we can't access res.0, construct ByteAt(a), ....

`/// load byte
pub fn ldb(state: &mut State, x: u8, y: u8, z: u8) {

    let op1: u64 = state.gpr[y].into();
    let op2: u64 = state.gpr[z].into();
    let a = op1.wrapping_add(op2);
    let address = ByteAt(a);
    let res = state.mem[address];
    let max_val = u8::max_value();
    if res.0 > max_val / 2 {
        let to_subtract = max_val - res.0;
        state.gpr[x] = Octa(u64::max_value() - (to_subtract as u64))
    } else {
        state.gpr[x] = Octa(res.0 as u64);
    }

}`

**Comment by teiesti** [comment]
There is a very simple tactic to work with these types, which is already fully implemented: `.into()`:

If you want to convert from u32 to Tetra:
```rust
let x: Tetra = 42u32.into();
```

If you want to convert from Tetra to f32:
```rust
let y: f32 = x.into(); // x is a Tetra, e.g. from above
```

This method works with any of these combinations:
- Byte: u8, i8
- Wyde: u16, i16
- Tetra: u32, i32, f32
- Octa: u64, i64, f64

If you need another combination: Please ask me and we'll see if this is a good idea! Lots of thoughts went into these types... (@KarolinePlum and I spent half a day working on the design!)

Please note, that .into() will only reinterpret the bits, since this is what we need most of the time. It does not "round" from float to integer, because we can easily do this with a cast.

**Comment by BarbaraButz** [comment]
Ah sorry, you're right - there is no problem with Byte/Wyde/Tetra/Octa. (Don't know what I was thinking...)
However, I still don't get how to construct e.g. a ByteAt.
like here:
`let address = ByteAt(a);`
This won't work, because the field of ByteAt is private and I didn't see any into-/from-implementation for the -At-Types.
(Sorry if I am - again - missing something obvious... 🙈)

**Comment by teiesti** [comment]
You don't have to be sorry for asking questions. Since there is no documentation at the moment, this is the only way for you to understand what the others did.

Let me answer the specific question: This is - again - a bug. You're totally right in how to instantiate the ByteAt. If you want to access a memory field, this is idiomatic code:
```rust
let x = mem[ByteAt(32)]; // mem is memory, x will be a Byte
```

I will fix that bug.
