### ISSUE TITLE
Implement the instruction set

### ISSUE THREAD

**Issue by teiesti** [MMXVII/mmix#5]
- [x] arithmetic ( #26 ) **merged**
- [x] bitwise ( #24 ) **merged**
- [x] bytewise ( #29 ) **merged**
- [x] conditional ( #28 ) **merged**
- [x] control ( #39 ) **merged**
- [x] float ( #37 ) **merged**
- [x] immediate ( #32 ) **merged**
- [ ] interrupt
- [x] memory ( #33 ) **merged**
- [x] other ( #38 ) **merged**
- [x] subroutine (work in progress)
- [x] system ( #41 ) **merged**

**Comment by teiesti** [comment]
@BarbaraButz, @jaborn: If you have questions how you can proceed, please ask!

**Comment by teiesti** [comment]
Since @KarolinePlum wrote the function signatures in #15: Please do not start as long as this pull-request is not merged. Otherwise, we will run into merge-conflicts... ;-)

**Comment by BarbaraButz** [comment]
@KarolinePlum Concerning the (load-/store-)[i]-instructions: Should'nt z be of type u64 (instead of u8)? Or am I missing something?

**Comment by KarolinePlum** [comment]
@BarbaraButz How can Z be an `u64` when the entire instruction is only `u32`? For LDB, $Y and $Z designate general purpose registers. For LDBI, $Y designates a general purpose register and Z an immediate constant of one byte.

**Comment by BarbaraButz** [comment]
bitwise instructions are implemented (not yet reviewed) #24

**Comment by jaborn** [comment]
I don't really know what the instruction, for example, 'addi' and 'addui' do in distinction from 'add' and 'addu'. 
Who can help me?

**Comment by jonas-schievink** [comment]
Without reading the spec, sounds like "add immediate", so this adds a value encoded in the instruction instead of a register value

**Comment by teiesti** [comment]
book, page 19, "The complete instrution set": It is add immediate!

**Comment by jaborn** [comment]
I've found it. Thanks.

**Comment by BarbaraButz** [comment]
concerning bytewise::{bdifi, wdifi, tdifi, odifi}:
Am I right in assuming that these four operators lead to the exact same outcome?
Or is z subtracted from each byte, wide, tetra and not only from the last?
(The former is my interpretation of the description in the book, but the latter would make more sense to me.)
~~Which leads me to another question: May I call an instruction from the body of another instruction?
Or should I refrain from doing that?
(I saw there was some disagreement on that matter.)~~

**Comment by KarolinePlum** [comment]
@BarbaraButz I think that the four immediate instructions do in fact lead to different outcomes. No, the value Z is not substracted from each byte / wyde / tetra / octa. I understand that in this case Z represents an Octabyte of the same value as the 8 bit that are passed. Therefore the leading 7 Bytes of the Octabyte Z would be zeros.

Example:
Let z be  255 and let the value of the Y register be 65280.

Then:
0x000000000000FF00      // Octabyte in Y register
0x00000000000000FF      // Octabyte Z

Result of BDIFI (bytewise):
0x000000000000FF00 // least significant byte will be set to zero because difference is negative
Result of WDIFI (wydewise):
0x000000000000FE01

**Comment by BarbaraButz** [comment]
You're right! Thanks!
