### ISSUE TITLE
Implement the main memory

### ISSUE THREAD

**Issue by teiesti** [MMXVII/mmix#6]

**Comment by KarolinePlum** [comment]
@teiesti At the moment I am not so sure anymore that what we intended is actually feasible.
Let's assume Memory has a HashMap that maps u64 to Byte. Implementing the Index and IndexMut Traits for ByteAt would be no problem then. But with e.g. WydeAt we would have to somehow craft a new Wyde object from two Bytes in the IndexMut method, and a return a reference to that. This reference would of course not live long enough!

**Comment by LukasKalbertodt** [comment]
How is this memory mapping supposed to work? So you have 64 bit wide addresses? Does MMIX has a MMU (memory mapping unit)? Does the notion of physical vs. virtual addresses exist in the specification? Could you link to the relevant section of the specification, please? ^_^

In any case, I think a `HashMap` (or `BTreeMap`) is not the right choice. If you have block-wise memory mapping, an interval-tree seems to be a good data structure for querying.

In order to make this `WydeAt`, `ByteAt`, etc stuff work, you have to make sure that adjacent addresses are also adjacent in your real memory. You can't just use a hash map with one entry for each byte, as this wouldn't allow returning a reference to a `Wyde` (whatever that is :P) for the reasons @KarolinePlum mentioned above. Furthermore it would be incredibly slow, as normal programs (e.g. running on your VM) will often access big contiguous chunks of memory. These chunks should be contiguous in the real memory, too.

But if you could provide more information about the problem, my comments would be more useful 😄

**Comment by KarolinePlum** [comment]
@LukasKalbertodt 
Yes, MMIX does distinguish between physical and virtual addresses. The mapping is explained [here](http://mmix.cs.hm.edu/doc/mmix-doc.pdf) on pages 35-39. This seems to  be really complicated stuff, and I am not understanding it completely at the moment. I guess we all thought this was easier than it actually is.

MMIX has a theoretical memory space of 2^64 bytes. You can get Bytes, Wydes (16 bit), Tetras (32 bit) and Octas (64 bit) from memory, all using 64-bit addresses. Every Byte in memory has exactly one address, but Wydes have two valid addresses.
Ɐk: `M[WydeAt(2k)] = M[WydeAt(2k + 1)]`
Consequently every Octa has 8 valid addresses. 
Ɐk: `M[OctaAt(8k)] = M[OctaAt(8k + 1)] = ... = M[OctaAt(8k + 7)]`

**Comment by jonas-schievink** [comment]
@KarolinePlum The PDF is really well written, and while the translation algorithm does look pretty complicated, it's explained quite well. Of course, since MMIX isn't a toy processor (it almost achieves feature-parity with other modern 64-bit processors), the most powerful feature shared by modern architectures isn't going to be trivial ;)

Address translation is done on a page-by-page basis (like on any modern processor), so you won't need to map individual bytes (fortunately!). However, the page size is configured by the current value in `rV`, so it can change during program runtime (this is madness!), which makes the system a bit more complicated.

The last part just means that access of larger words will mask the lowest bit(s), rounding down the address to one that is divisible by the word size in bytes (2, 4 or 8).

**Comment by LukasKalbertodt** [comment]
One useful trick is to ignore all information that is only relevant to the operating system. As I (!!) understand it, the special register rV as well as all the PTEs are written by the operating system, so you "just" have to interpret those.

So your algorithm for virtual address A should look a bit like this:

1. Is the first bit of A set? If yes, unset that bit to get the physical address.
2. Obtain the segment id *i* = A/2^61
3. Use rV to calculate the physical address of the PTE of the page containing A 
  - For the first 1024 pages it's  `m8[2^13 * (r + b_i) + A/2^s`
  - For pages

**Comment by LukasKalbertodt** [comment]
(sorry, I hit submit too early 😉 )

One useful trick is to ignore all information that is only relevant to the operating system. As I (!!) understand it, the special register rV as well as all the PTEs are written by the operating system, so you "just" have to interpret those.

So your algorithm for the virtual address A should look a bit like this:

1. Is the first bit of A set? If yes, unset that bit to get the physical address. If no, continue.
2. Obtain the segment id *i* = A/2^61
3. Use rV to calculate the physical address of the PTE representing the page containing A 
    - For the first 1024 pages it's  `m8[2^13 * (r + b_i) + A/2^s]`
    - For the rest it's more complicated (I guess you can ignore that for now)
4. Use the PTE to calculate the physical address

With that said: how do you map the MMIX physical address to the host-address? First of all: I think you should fix the size of the physical memory on VM-startup. Pretending that all 2^48 physical addresses are accessible is madness IMO. If you look at virtual machines for x86 hardware, like VirtualBox or VMWare, you see that those also fix the available RAM before startup.

With a fixed memory size, you could simply use a `Vec<u8>` that holds as many bytes as physically accessible. This is easy and a good way to start. 

If you want, you can talk to me in person about this, maybe I can help (unfortunately, though, I don't have much time after the lecture tomorrow).

**Comment by teiesti** [comment]
@KarolinePlum: Since my time is limited and this looks really complicated I would prefer to talk about that in person. Otherwise we waste time in writing comments that we desperately need to actually implement things.

**Comment by KarolinePlum** [comment]
Yes, let's absolutely talk about this in person :)

**Comment by teiesti** [comment]
PR is merged: Issue closed.
